namespace MyRTSGame.Model
{
    public enum BuildingType
    {
        School,
        Restaurant,
        Warehouse,
        StoneQuarry,
        LumberJack,
        SawMill,
        WeaponsWorkshop,
        ArmorWorkshop,
        WheatFarm,
        Mill,
        Bakery,
        PigFarm,
        Butcher,
        Tannery,
        GoldMine,
        CoalMine,
        IronMine,
        GoldSmelter,
        IronSmelter,
        WeaponsSmith,
        ArmorSmith,
        Vineyard,
        FisherMansHut,
        Stable,
        SiegeWorkshop,
    }
}