namespace Enums
{
    public enum ResourceType
    {
        Stone,
        Lumber,
        Wood,
        Wheat,
        Flour,
        Bread,
        Pork,
        Hides,
        Leather,
        Sausage,
        Wine,
        Coal,
        IronOre,
        GoldOre,
        Iron,
        Gold,
        Spear,
        Axe,
        Bow,
        Sword,
        Pike,
        CrossBow,
        LeatherArmor,
        IronArmor,
        WoodenShield,
        IronShield,
        Horses,
        Fish,
    }
}